### ISSUE TITLE
input validation

### ISSUE THREAD

**Issue by boardgame1** [Aunsiels/alphazero_janggi#2]
In game.py run_game function please add input validation routine.

            if self.current_player == human_player:
                print(self.round, end=' ')
                actions = self.get_current_actions()
                while True:
                    new_action = self.get_next_action()
                    if new_action in actions or\
                            (new_action.x_from==new_action.x_to and new_action.y_from==new_action.y_to):
                        break
                    else:
                        print("Invalid Action")
            else:
                new_action = self.get_next_action()

**Comment by Aunsiels** [comment]
Hello,

Thank you for your suggestion. It was implemented in commit 5884af5bd94aaade2d078528233349fe2f4205d3
